// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoywM9O7kIrAqti8c1tyFwOJ1EZrMRwrI',
    appId: '1:307700719288:web:d8e056ebfda31307235e4d',
    messagingSenderId: '307700719288',
    projectId: 'sights-app-bc029',
    authDomain: 'sights-app-bc029.firebaseapp.com',
    storageBucket: 'sights-app-bc029.firebasestorage.app',
    measurementId: 'G-GPEF9KTHQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr9vmK-gtB5UCsJ3xBj72MPQM_luRjDzs',
    appId: '1:307700719288:android:2183005887d23490235e4d',
    messagingSenderId: '307700719288',
    projectId: 'sights-app-bc029',
    storageBucket: 'sights-app-bc029.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkSlDkUu4ajBoixxAnCo9b4cPY1l0voDI',
    appId: '1:307700719288:ios:9f3b23d35a7709a2235e4d',
    messagingSenderId: '307700719288',
    projectId: 'sights-app-bc029',
    storageBucket: 'sights-app-bc029.firebasestorage.app',
    iosBundleId: 'hr.algebra.sightsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoywM9O7kIrAqti8c1tyFwOJ1EZrMRwrI',
    appId: '1:307700719288:web:9a89304cb4d031f9235e4d',
    messagingSenderId: '307700719288',
    projectId: 'sights-app-bc029',
    authDomain: 'sights-app-bc029.firebaseapp.com',
    storageBucket: 'sights-app-bc029.firebasestorage.app',
    measurementId: 'G-QNGZS708R6',
  );

}